/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/integrations/host/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a batch of orders
         * @description Each order is processed independently and gets its own result: ACCEPTED, DUPLICATE (an order with this external reference already exists and was not changed), or REJECTED with field errors. Returns 200 whenever the batch itself is well formed, even if every order was rejected.
         */
        post: operations["importOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inventory balances
         * @description Stock per location and SKU. Balances with nothing on hand or allocated are omitted unless includeEmpty is true.
         */
        get: operations["listBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct stock at a location
         * @description A signed correction with a mandatory reason, e.g. -4 for damaged units.
         */
        post: operations["recordAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move stock between locations
         * @description For example replenishment from reserve to forward-pick. All or nothing.
         */
        post: operations["recordMove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive stock into a location */
        post: operations["recordReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ledger entries
         * @description Newest first.
         */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ledger entry */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations
         * @description Optionally filtered by zone code and location type.
         */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a location
         * @description Includes the pick slot for forward-pick locations.
         */
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description In the order they were received.
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{externalRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order with its lines */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SKUs */
        get: operations["listSkus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a SKU */
        get: operations["getSku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/{code}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a SKU's availability
         * @description Totals across the warehouse, broken down by location type (forward-pick, reserve, ...).
         */
        get: operations["getSkuAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List waves */
        get: operations["listWaves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waves/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a wave
         * @description Selects open orders, promises stock, and creates pick tasks plus the replenishment they depend on. With preview=true nothing is written and no stock is locked; the result is advisory.
         */
        post: operations["planWave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waves/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a wave with its orders and task counts */
        get: operations["getWave"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waves/{number}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a planned wave
         * @description Cancels its work, releases the stock it promised, and returns its orders to RECEIVED.
         */
        post: operations["cancelWave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waves/{number}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a wave to the floor */
        post: operations["releaseWave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List zones */
        get: operations["listZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActorView: {
            id: string;
            /** @enum {string} */
            type: "HUMAN" | "AGENT" | "SYSTEM" | "INTEGRATION";
        };
        AdjustmentRequest: {
            location: string;
            /**
             * Format: int32
             * @description Signed change: positive adds stock, negative removes it. Must not be 0.
             */
            quantity: number;
            reason: string;
            sku: string;
        };
        BalanceView: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            location: string;
            /** @enum {string} */
            locationType: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            /** Format: int32 */
            onHand: number;
            sku: string;
            zone: string;
        };
        FieldError: {
            field: string;
            message: string;
        };
        HostOrder: {
            carrier: string;
            /** Format: date-time */
            carrierCutoffAt: string;
            customer: string;
            externalRef: string;
            lines: components["schemas"]["HostOrderLine"][];
            /**
             * Format: int32
             * @description 1 (most urgent) to 5; defaults to 3
             */
            priority?: number | null;
        };
        HostOrderLine: {
            /** Format: int32 */
            lineNo: number;
            /** Format: int32 */
            quantity: number;
            sku: string;
        };
        LocationTypeAvailability: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            /** @enum {string} */
            locationType: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            /** Format: int32 */
            locations: number;
            /** Format: int32 */
            onHand: number;
        };
        LocationView: {
            active: boolean;
            /** Format: int32 */
            capacityUnits?: number | null;
            code: string;
            /**
             * Format: int32
             * @description Walking order for pick-path sequencing
             */
            pickSequence?: number | null;
            /** @description Set for forward-pick slots */
            pickSlot?: components["schemas"]["PickSlotView"] | null;
            /** @description Equipment needed to reach it, e.g. REACH_TRUCK */
            requiredEquipment?: string | null;
            /** @enum {string} */
            type: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            zone: string;
        };
        MoveRequest: {
            fromLocation: string;
            /** Format: int32 */
            quantity: number;
            sku: string;
            toLocation: string;
        };
        MovementResultView: {
            balances: components["schemas"]["BalanceView"][];
            transaction: components["schemas"]["TransactionView"];
        };
        OrderImportRequest: {
            orders: components["schemas"]["HostOrder"][];
        };
        OrderImportResponse: {
            /** Format: int32 */
            accepted: number;
            /** Format: int32 */
            duplicates: number;
            /** Format: int32 */
            rejected: number;
            results: components["schemas"]["OrderResult"][];
        };
        OrderLineView: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            lineNo: number;
            /** Format: int32 */
            ordered: number;
            /** Format: int32 */
            picked: number;
            /** Format: int32 */
            shipped: number;
            /** Format: int32 */
            shortQuantity: number;
            sku: string;
        };
        OrderResult: {
            errors: components["schemas"]["FieldError"][];
            /** @description Null only if the order had no reference */
            externalRef?: string | null;
            /** @enum {string} */
            result: "ACCEPTED" | "DUPLICATE" | "REJECTED";
        };
        OrderSummaryView: {
            carrier: string;
            /** Format: date-time */
            carrierCutoffAt: string;
            customer: string;
            externalRef: string;
            holdReason?: string | null;
            /** Format: int32 */
            lines: number;
            onHold: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: date-time */
            receivedAt: string;
            /**
             * Format: int32
             * @description Units ordered but not allocated
             */
            shortQuantity: number;
            /** @enum {string} */
            status: "RECEIVED" | "ALLOCATED" | "RELEASED" | "PICKING" | "PICKED" | "PACKED" | "SHIPPED" | "CANCELLED";
            /** Format: int32 */
            unitsAllocated: number;
            /** Format: int32 */
            unitsOrdered: number;
        };
        OrderView: {
            carrier: string;
            /** Format: date-time */
            carrierCutoffAt: string;
            customer: string;
            externalRef: string;
            holdReason?: string | null;
            lines: components["schemas"]["OrderLineView"][];
            onHold: boolean;
            /** Format: int32 */
            priority: number;
            /** Format: date-time */
            receivedAt: string;
            /** @enum {string} */
            status: "RECEIVED" | "ALLOCATED" | "RELEASED" | "PICKING" | "PICKED" | "PACKED" | "SHIPPED" | "CANCELLED";
        };
        PageBalanceView: {
            items: components["schemas"]["BalanceView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageLocationView: {
            items: components["schemas"]["LocationView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageOrderSummaryView: {
            items: components["schemas"]["OrderSummaryView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageSkuView: {
            items: components["schemas"]["SkuView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageTransactionView: {
            items: components["schemas"]["TransactionView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageWaveSummaryView: {
            items: components["schemas"]["WaveSummaryView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageZoneView: {
            items: components["schemas"]["ZoneView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PickSlotView: {
            /** Format: int32 */
            maxQty: number;
            /** Format: int32 */
            minQty: number;
            sku: string;
        };
        PlanResultView: {
            /** Format: int32 */
            orders: number;
            /** Format: int32 */
            pickTasks: number;
            preview: boolean;
            /** Format: int32 */
            replenishmentTasks: number;
            shortages: components["schemas"]["ShortageView"][];
            /** Format: int32 */
            unitsAllocated: number;
            /**
             * Format: int32
             * @description Units that could not be covered for orders in this wave
             */
            unitsShort: number;
            /**
             * Format: int64
             * @description Null for a preview, or when there was nothing to plan
             */
            waveNumber?: number | null;
        };
        PlanWaveRequest: {
            /** @description Only orders for this carrier */
            carrier?: string | null;
            /**
             * Format: int32
             * @description Only orders whose carrier cutoff is within this many hours
             */
            cutoffWithinHours?: number | null;
            /**
             * Format: int32
             * @description How many orders the wave may cover; default 50
             */
            maxOrders?: number | null;
        };
        Quantities: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            /** Format: int32 */
            onHand: number;
        };
        ReceiptRequest: {
            location: string;
            /** Format: int32 */
            quantity: number;
            /** @description What the receipt belongs to, e.g. a purchase order */
            reference?: components["schemas"]["ReferenceBody"] | null;
            sku: string;
        };
        ReferenceBody: {
            id: string;
            type: string;
        };
        ReferenceView: {
            id: string;
            type: string;
        };
        ShortageView: {
            order: string;
            /** Format: int32 */
            quantity: number;
            sku: string;
        };
        SkuAvailabilityView: {
            byLocationType: components["schemas"]["LocationTypeAvailability"][];
            sku: string;
            total: components["schemas"]["Quantities"];
        };
        SkuView: {
            active: boolean;
            code: string;
            description: string;
            uom: string;
            /** @enum {string|null} */
            velocityClass?: "A" | "B" | "C" | null;
        };
        TaskCounts: {
            /** Format: int32 */
            assigned: number;
            /** Format: int32 */
            cancelled: number;
            /** Format: int32 */
            completed: number;
            /** Format: int32 */
            inProgress: number;
            /** Format: int32 */
            ready: number;
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            waiting: number;
        };
        TransactionView: {
            actor: components["schemas"]["ActorView"];
            fromLocation?: string | null;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int32 */
            quantity: number;
            reason?: string | null;
            reference?: components["schemas"]["ReferenceView"] | null;
            sku: string;
            toLocation?: string | null;
            /** @enum {string} */
            type: "RECEIPT" | "PICK" | "MOVE" | "ADJUST" | "COUNT_VARIANCE";
        };
        WaveOrderView: {
            /** Format: date-time */
            carrierCutoffAt: string;
            customer: string;
            externalRef: string;
            /** Format: int32 */
            priority: number;
            status: string;
            /** Format: int32 */
            unitsAllocated: number;
            /** Format: int32 */
            unitsOrdered: number;
        };
        WaveSummaryView: {
            /** Format: int64 */
            number: number;
            /** Format: int32 */
            orders: number;
            /** Format: date-time */
            plannedAt: string;
            /** Format: date-time */
            releasedAt?: string | null;
            status: string;
            tasks: components["schemas"]["TaskCounts"];
            /** Format: int32 */
            unitsAllocated: number;
        };
        WaveView: {
            /** Format: int64 */
            number: number;
            orders: components["schemas"]["WaveOrderView"][];
            /** Format: date-time */
            plannedAt: string;
            /** Format: date-time */
            releasedAt?: string | null;
            status: string;
            tasks: components["schemas"]["TaskCounts"];
            /** Format: int32 */
            unitsAllocated: number;
        };
        ZoneView: {
            code: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    importOrders: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderImportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderImportResponse"];
                };
            };
        };
    };
    listBalances: {
        parameters: {
            query?: {
                sku?: string;
                location?: string;
                zone?: string;
                type?: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
                includeEmpty?: boolean;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageBalanceView"];
                };
            };
        };
    };
    recordAdjustment: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovementResultView"];
                };
            };
        };
    };
    recordMove: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovementResultView"];
                };
            };
        };
    };
    recordReceipt: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MovementResultView"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                sku?: string;
                location?: string;
                type?: "RECEIPT" | "PICK" | "MOVE" | "ADJUST" | "COUNT_VARIANCE";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTransactionView"];
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                zone?: string;
                type?: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageLocationView"];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationView"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                status?: "RECEIVED" | "ALLOCATED" | "RELEASED" | "PICKING" | "PICKED" | "PACKED" | "SHIPPED" | "CANCELLED";
                onHold?: boolean;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageOrderSummaryView"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                externalRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"];
                };
            };
        };
    };
    listSkus: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSkuView"];
                };
            };
        };
    };
    getSku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkuView"];
                };
            };
        };
    };
    getSkuAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkuAvailabilityView"];
                };
            };
        };
    };
    listWaves: {
        parameters: {
            query?: {
                status?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageWaveSummaryView"];
                };
            };
        };
    };
    planWave: {
        parameters: {
            query?: {
                preview?: boolean;
            };
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlanWaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanResultView"];
                };
            };
        };
    };
    getWave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaveView"];
                };
            };
        };
    };
    cancelWave: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaveView"];
                };
            };
        };
    };
    releaseWave: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per logical request. Retrying with the same key returns the original response instead of repeating the command. */
                "Idempotency-Key": string;
            };
            path: {
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaveView"];
                };
            };
        };
    };
    listZones: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageZoneView"];
                };
            };
        };
    };
}
