/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inventory balances
         * @description Stock per location and SKU. Balances with nothing on hand or allocated are omitted unless includeEmpty is true.
         */
        get: operations["listBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations
         * @description Optionally filtered by zone code and location type.
         */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a location
         * @description Includes the pick slot for forward-pick locations.
         */
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SKUs */
        get: operations["listSkus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a SKU */
        get: operations["getSku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/{code}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a SKU's availability
         * @description Totals across the warehouse, broken down by location type (forward-pick, reserve, ...).
         */
        get: operations["getSkuAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List zones */
        get: operations["listZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BalanceView: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            location: string;
            /** @enum {string} */
            locationType: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            /** Format: int32 */
            onHand: number;
            sku: string;
            zone: string;
        };
        LocationTypeAvailability: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            /** @enum {string} */
            locationType: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            /** Format: int32 */
            locations: number;
            /** Format: int32 */
            onHand: number;
        };
        LocationView: {
            active: boolean;
            /** Format: int32 */
            capacityUnits?: number | null;
            code: string;
            /**
             * Format: int32
             * @description Walking order for pick-path sequencing
             */
            pickSequence?: number | null;
            /** @description Set for forward-pick slots */
            pickSlot?: components["schemas"]["PickSlotView"] | null;
            /** @description Equipment needed to reach it, e.g. REACH_TRUCK */
            requiredEquipment?: string | null;
            /** @enum {string} */
            type: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
            zone: string;
        };
        PageBalanceView: {
            items: components["schemas"]["BalanceView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageLocationView: {
            items: components["schemas"]["LocationView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageSkuView: {
            items: components["schemas"]["SkuView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PageZoneView: {
            items: components["schemas"]["ZoneView"][];
            /** @description Opaque cursor for the next page; null on the last page */
            nextCursor?: string | null;
        };
        PickSlotView: {
            /** Format: int32 */
            maxQty: number;
            /** Format: int32 */
            minQty: number;
            sku: string;
        };
        Quantities: {
            /** Format: int32 */
            allocated: number;
            /** Format: int32 */
            available: number;
            /** Format: int32 */
            onHand: number;
        };
        SkuAvailabilityView: {
            byLocationType: components["schemas"]["LocationTypeAvailability"][];
            sku: string;
            total: components["schemas"]["Quantities"];
        };
        SkuView: {
            active: boolean;
            code: string;
            description: string;
            uom: string;
            /** @enum {string|null} */
            velocityClass?: "A" | "B" | "C" | null;
        };
        ZoneView: {
            code: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBalances: {
        parameters: {
            query?: {
                sku?: string;
                location?: string;
                zone?: string;
                type?: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
                includeEmpty?: boolean;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageBalanceView"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                zone?: string;
                type?: "FORWARD_PICK" | "RESERVE" | "STAGING" | "PACK" | "DOCK";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageLocationView"];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationView"];
                };
            };
        };
    };
    listSkus: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSkuView"];
                };
            };
        };
    };
    getSku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkuView"];
                };
            };
        };
    };
    getSkuAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkuAvailabilityView"];
                };
            };
        };
    };
    listZones: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageZoneView"];
                };
            };
        };
    };
}
